Add addresses to /etc/hosts better -- include ipv6 address too

diff --git a/bin/run-job b/bin/run-job
--- a/bin/run-job
+++ b/bin/run-job
@@ -40,6 +40,41 @@ run_command_with_retries()
     return 1
 }
 
+
+add_addresses_to_etc_hosts()
+{
+    python3 -c '
+import json
+import subprocess as sp
+
+# Load interface info as JSON; this returns an array of interfaces
+ifaces = json.loads(sp.check_output(["ip", "-j", "addr"])  # type: list
+v4_addresses = []
+v6_addresses = []
+
+for iface in ifaces:
+    if iface["link_type"] == "loopback":
+        continue
+    if "UP" not in iface["flags"]:
+        continue
+    for addr in addr_info:
+        family = addr["family"]
+        ip = addr["local"]
+        if ip.startswith("127.") or ip == "::1" or ip.startswith("fe80"):
+            continue
+        if family == "inet":
+            v4_addresses.append(ip)
+        elif family == "inet6":
+            v6_addresses.append(ip)
+
+with open("/etc/hosts", "a") as hostsfh:
+    for ip in v4_addresses:
+        hostsfh.write("%s osg-test.localdomain osg-test\n")
+    for ip in v6_addresses:
+        hostsfh.write("%s osg-test.localdomain osg-test\n")
+'
+}
+
 # Figure out OSG release series
 osg_series=`grep series $INPUT_DIR/osg-test.conf | sed -e 's/series *= *//'`
 
@@ -90,17 +125,18 @@ log_command mount
 log_command cat /proc/net/dev
 
 # Set a hostname
-if [[ -n `ip addr | grep eth0` ]]; then
-    ip_address=`ip addr show eth0 | awk 'match($0, /inet ([0-9.]+)/, a) { print a[1] }'`
-elif [[ -n `ip addr | grep ens3` ]]; then
-    ip_address=`ip addr show ens3 | awk 'match($0, /inet ([0-9.]+)/, a) { print a[1] }'`
-elif [[ -n `ip addr | grep enp1s0` ]]; then
-    ip_address=`ip addr show enp1s0 | awk 'match($0, /inet ([0-9.]+)/, a) { print a[1] }'`
-else
-    echo 'Could not find IP address'
-    exit 1
-fi
-echo "$ip_address osg-test.localdomain osg-test" >> /etc/hosts
+# if [[ -n `ip addr | grep eth0` ]]; then
+#     ip_address=`ip addr show eth0 | awk 'match($0, /inet ([0-9.]+)/, a) { print a[1] }'`
+# elif [[ -n `ip addr | grep ens3` ]]; then
+#     ip_address=`ip addr show ens3 | awk 'match($0, /inet ([0-9.]+)/, a) { print a[1] }'`
+# elif [[ -n `ip addr | grep enp1s0` ]]; then
+#     ip_address=`ip addr show enp1s0 | awk 'match($0, /inet ([0-9.]+)/, a) { print a[1] }'`
+# else
+#     echo 'Could not find IP address'
+#     exit 1
+# fi
+# echo "$ip_address osg-test.localdomain osg-test" >> /etc/hosts
+add_addresses_to_etc_hosts
 log_command cat /etc/hosts
 log_command cat /etc/host.conf
 log_command hostname
